module.exports = {
    iso8601DurationRegex: /^P(?!$)(?:(\d+Y)?(\d+M)?(\d+D)?)(T(?=\d)(\d+H)?(\d+M)?(\d+(?:\.\d+)?S)?)?$/,
    urlRegex: /^(ftp|http|https):\/\/[^ "]+$/,
    isoTime: /^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.\d{3})?(Z|(\+00:00))?$/,
    orderArray: [
        "CRD_1", "CRD_2", "CRD_3", "CRD_4", "CRD_5", "CRD_6", "CRD_7",
        "CRD_8", "CRD_9", "CRD_10", "CRD_11", "CRD_12", "CRD_13", "CRD_14",
        "INS_1", "INS_2", "INS_3", "INS_4", "INS_5", "INS_6", "INS_7",
        "INS_8", "INS_9", "INS_10", "INS_11", "INS_12", "INS_13", "INS_14",
        "INS_15", "INS_16", "INS_17", "INS_18", "INS_19", "MBL_1", "MBL_2",
        "MBL_3", "MBL_4", "MBL_5", "MBL_6", "MBL_20", "MBL_7", "MBL_8", "MBL_9", "MBL_10",
        "MBL_11", "MBL_12", "MBL_13", "MBL_14", "AIR_1", "AIR_2", "AIR_3", "AIR_4",
        "DEM_2A", "DEM_2B", "DEM_2", "DEM_3", "DEM_4", "DEM_5", "DEM_6", "DEM_1A", "DEM_1B", "DEM_7",
        "INVESTMENT_1", "INVESTMENT_2", "INVESTMENT_3", "INVESTMENT_4", "INVESTMENT_5",
        "INVESTMENT_6", "INVESTMENT_7", "INVESTMENT_8", "GIFTCARD_1", "GIFTCARD_2", "GIFTCARD_3",
        "GIFTCARD_4", "GIFTCARD_5", "B2C_1", "B2C_2", "B2C_3", "B2C_4", "B2C_5",
        "B2C_6", "B2C_7", "RET_1", "RET_1b", "RET_2", "RET_3", "RET_4", "RET_4b", "RET_4c", "RET_5", "RET_5b", "RET_6",
        "RET_7", "RET_8", "RET_9", "RET_10", "RET_11", "RET_12", "RET_13", "RET_14", "RET_15", "PUR_1", "PUR_2",
        "PUR_3", "PUR_4", "PUR_5", "PUR_6", "PUR_7", "PUR_8", "IGM_1", "IGM_2", "IGM_3", "IGM_4", "B2C_1", "B2C_2", "B2C_3", "B2C_4", "B2C_5", "B2C_7",
        "LOG10_1", "LOG10_2", "LOG10_3", "LOG10_4", "LOG10_5", "LOG10_6", "LOG10_7", "LOG10COD", "LOG10SURGFEE", "LOG10_8"
    ],
    mutualFundCategories: ["MUTUAL_FUNDS", "OPEN_ENDED", "OPEN_ENDED_EQUITY", "OPEN_ENDED_EQUITY_MIDCAP", "OPEN_ENDED_DEBT", "OPEN_ENDED_SOLUTION_ORIENTED", "OPEN_ENDED_OTHER", "OPEN_ENDED_HYBRID", "OPEN_ENDED_HYBRID_AGGRESSIVE_HYBRID_FUND", "OPEN_ENDED_HYBRID_BALANCED_HYBRID_FUND", "OPEN_ENDED_EQUITY_FLEXI_CAP_FUND", "OPEN_ENDED_DEBT_DYNAMIC_BOND", "OPEN_ENDED_DEBT_MEDIUM_DURATION_FUND", "OPEN_ENDED_DEBT_MONEY_MARKET_FUND", "OPEN_ENDED_EQUITY_DIVIDEND_YIELD_FUND", "OPEN_ENDED_DEBT_GILT_FUND_WITH_10_YEAR_CONSTANT_DURATION", "OPEN_ENDED_EQUITY_ELSS", "OPEN_ENDED_DEBT_ULTRA_SHORT_DURATION_FUND", "OPEN_ENDED_DEBT_LIQUID_FUND", "OPEN_ENDED_DEBT_LONG_DURATION_FUND", "OPEN_ENDED_DEBT_GILT_FUND", "OPEN_ENDED_EQUITY_MULTI_CAP_FUND", "OPEN_ENDED_HYBRID_ARBITRAGE FUND", "OPEN_ENDED_SOLUTION_ORIENTED_RETIREMENT_FUND", "OPEN_ENDED_DEBT_OVERNIGHT_FUND", "OPEN_ENDED_EQUITY_LARGE_CAP_FUND", "OPEN_ENDED_OTHER_FOF_DOMESTIC", "OPEN_ENDED_EQUITY_SECTORAL_THEMATIC", "OPEN_ENDED_EQUITY_MID_CAP_FUND", "OPEN_ENDED_OTHER_INDEX_FUNDS", "OPEN_ENDED_EQUITY_LARGE_MID_CAP_FUND", "OPEN_ENDED_DEBT_BANKING_AND_PSU_FUND", "OPEN_ENDED_DEBT_LOW_DURATION_FUND", "OPEN_ENDED_EQUITY_FOCUSED_FUND", "OPEN_ENDED_SOLUTION_ORIENTED", "OPEN_ENDED_EQUITY_CONTRA_FUND", "OPEN_ENDED_HYBRID_MULTI_ASSET_ALLOCATION", "OPEN_ENDED_OTHER_FOF_OVERSEAS", "OPEN_ENDED_EQUITY_SMALL_CAP_FUND", "OPEN_ENDED HYBRID_EQUITY SAVINGS", "OPEN_ENDED_OTHER_OTHER_ETFS", "OPEN_ENDED_DEBT_CREDIT_RISK_FUND", "OPEN_ENDED_EQUITY_VALUE_FUND", "OPEN_ENDED_SOLUTION_ORIENTED_CHILDREN_FUN", "OPEN_ENDED HYBRID_CONSERVATIVE_HYBRID_FUND", "OPEN_ENDED_DEBT_MEDIUM_TO_LONG_DURATION_FUND", "OPEN_ENDED_HYBRID_DYNAMIC_ASSET_ALLOCATION_OR_BALANCED_ADVANTAGE", "OPEN_ENDED_DEBT CORPORATE_BOND_FUND", "OPEN_ENDED_DEBT_SHORT_DURATION_FUND"]
}